service: woaka-services
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'ses:SendTemplatedEmail'
          Resource: '*'
  environment:
    destination: soporte@gurusaws.com

package:
  individually: True
  patterns:
    - "!*/**"
    - "!**"

plugins:
  - serverless-offline


functions:
  send_email:
    handler: src/email/handler.send_email
    # timeout: 30
    name: ${opt:stage}-post-send-email
    package:
      patterns:
        - "main.py"
        - "routers/emailRouters.py"
        - "models/emailModels.py"
        - "services/emailsServices.py"
    events:
      - http:
          path: /api/v1/send-email-for-user
          method: post
          request:
            schemas:
              application/json: ${file(src/model/post_email.json)}
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
resources:
  Resources:
    template:
      Type: AWS::SES::Template
      Properties:
        Template:
          HtmlPart: ${file(inbox.html)}
          SubjectPart: inbox-woaka
          TemplateName: inbox_woaka